### ISSUE TITLE
Not all listed projects full satisfy the CONTRIBUTING.md guide

### ISSUE THREAD

**Issue by codehakase** [acekyd/made-in-nigeria#113]
Hey people!

Recently I've been closing and commenting on incoming pull requests, majority of which doesn't fully satisfy this guide https://github.com/acekyd/made-in-nigeria/blob/master/contributing.md

I just check the list, and the very first project doesn't.

Are we to remove the ones not satisfying the guide, or merge the previous PRs that have been sent?

**Comment by acekyd** [comment]
Hey... Clean up has been something I have been intending to do myself. If you are able to go through the projects listed and remove those not satisfying the criteria, a PR will be great. @codehakase

**Comment by codehakase** [comment]
@acekyd sure! will do so this week
