### ISSUE TITLE
How to Volunteer as a Moderator

### ISSUE THREAD

**Issue by BolajiAyodeji** [acekyd/made-in-nigeria#118]
@acekyd how can I apply to moderate this project?

**Comment by whizkydee** [comment]
Hi @BolajiAyodeji,

We're gald you're interested in moderating this project. However, I don't think we need extra moderators at this time as we currently hanlde all the PRs.

We'll let you know if we're in need soon. Feel free to contribute in any other ways you can.

Thanks!

**Comment by BolajiAyodeji** [comment]
Alright @whizkydee 
Thanks for the response!
