### ISSUE TITLE
Load Languages Button not displaying Build languages for `NettyFinder`

### ISSUE THREAD

**Issue by BolajiAyodeji** [acekyd/made-in-nigeria#119]
I recently added my project to the collection, I tried viewing on the web version and I clicked the LOAD LANGUAGE button but it displayed nothing meanwhile other projects got some display.
What could be wrong?

**Comment by acekyd** [comment]
What project is this? @BolajiAyodeji

**Comment by acekyd** [comment]
The issue with this is the name is different from the URL to the project. I checked other projects satisfying the same condition and it's the same result. Will look into it @BolajiAyodeji. Thanks.

**Comment by BolajiAyodeji** [comment]
:+1:

**Comment by acekyd** [comment]
Your project name in the readme is "NettyFinder" and it's what is used to get the languages by passing that to a GitHub API. However, the link here on GitHub is actually Netty-Finder so it results in a broken link when trying to retrieve the languages. Which is what I'll be looking into fixing soon.

**Comment by BolajiAyodeji** [comment]
I totally understand now.
Should I change the name to match the URL or wait for your fix @acekyd

**Comment by acekyd** [comment]
Any is fine @BolajiAyodeji

**Comment by BolajiAyodeji** [comment]
> Any is fine @BolajiAyodeji

Alright
