### ISSUE TITLE
want to add my libraries to the list

### ISSUE THREAD

**Issue by jacobbogers** [acekyd/made-in-nigeria#161]
Hi ppls
I want to add my libraries to your list, 

https://github.com/R-js/libRmath.js 

https://github.com/R-js/blasjs 

https://github.com/R-js/mangos

Cheers

**Comment by acekyd** [comment]
Hello @jacobbogers.

Please check out the [contributing guide](https://github.com/acekyd/made-in-nigeria/blob/master/contributing.md) and send in a PR
