### ISSUE TITLE
Add link to each individual project github link or hosted url

### ISSUE THREAD

**Issue by Codehouze** [acekyd/made-in-nigeria#224]
Adding a link to each project would make it easily seen and used too.

**Comment by s0mt0chukwu** [comment]
> Adding a link to each project would make it easily seen and used too.

This repo is officially dead

**Comment by acekyd** [comment]
Hi! @Codehouze each project is already linked to the repository. Can you clarify what you mean by this?

**Comment by kaf-lamed-beyt** [comment]
Hi @acekyd,

What's the likelihood of merging some of the open PRs?

**Comment by acekyd** [comment]
> Hi @acekyd,
> 
> Unrelated to this issue; What's the likelihood of merging some of the open PRs?

Reviewing and merging at the moment.

**Comment by Codehouze** [comment]
@acekyd  I meant a link to each  project on git hub.. I made this comment a year ago. I think this has been fixed already.
