### ISSUE TITLE
Implement Creators section - A profile blog.

### ISSUE THREAD

**Issue by acekyd** [acekyd/made-in-nigeria#263]
Looking to create a File-based Markdown blog so that it can be in the repo as well for creators. This covers their profile - And the blog would be able to fetch data of the projects possibly from the stored state of Nextjs - this will be used to show the projects tied to the username of the profile being read on the blog.

**Comment by kaf-lamed-beyt** [comment]
If you don't mind.. I can work on this. 

My [blog](https://meje.dev) uses markdown — MDX. Is there a design available?

**Comment by acekyd** [comment]
Hey @kaf-lamed-beyt, nice to see you've done similar stuff with this on Next. Here are the [designs](https://www.figma.com/file/pEPCkthfdcKR5irTw1Vh59/Made-In-Nigeria.dev?type=design&node-id=0%3A1&mode=design&t=dzCaVQDVXQJldNEA-1). You can branch off the `web-dev` branch.

When do you think this could be ready?

**Comment by kaf-lamed-beyt** [comment]
I've got to say... This design looks so good! 

About its readiness... How does Saturday, next week sound to you? I chose Saturday because I don't know what the workload of the week would be like for me, just to have a good factor of safety. 

It could be ready before then too.

**Comment by acekyd** [comment]
Yes... Next Saturday works. Once you get into the branch, you might find some of the components already created that may assist in speeding up the process. Looking forward to the results. Thanks @kaf-lamed-beyt

**Comment by kaf-lamed-beyt** [comment]
Sweeet! Makes everything easier. 

Thank you @acekyd!

**Comment by kaf-lamed-beyt** [comment]
Few observations @acekyd. 

I noticed the project uses Next.js' appDir and by default, [Chakra components are not RSC compatible](https://github.com/chakra-ui/chakra-ui/issues/7209#issuecomment-1474920965) which is why the `use client` directive is almost in every React component that relies on a Chakra primitive, which is okay for client operations. 

But, the implementation of this blog kinda depends on the use of Node.js filesystem module &mdash; `fs()` &mdash; which is a server-side operation. 

So, if I decide to do something like this:

```ts
const articlesDirectory = path.join(process.cwd(), "/app/blog/articles");
```
Next would throw a "cannot find module 'fs' " error. Because we're attempting to perform a server operation in a component with the 'use client' directive. 

It is also not possible to use both `"use client"` and `"use server"` directives in a component. So, for now... I think Chakra is the culprit. But, the solution that comes to mind right now is to look for a way to use the Pages Dir router alongside the appDir, with `getStaticProps` and `getStaticPaths` if it is possible though. 

I tried doing it at first, but it ended up futile. Let me know what you think when you see this.

**Comment by acekyd** [comment]
Damn... I understand the challenge @kaf-lamed-beyt, and would want to avoid the inconsistencies as well. We wanted to use Chakra as a point of symbolism but wasn't aware of the complications. 

-Are you using a particular tool for the blog I could check out to see if I can come up with alternative ways to approach this?
- Wondering what the possible implication is if we move the chakra ui components and pages to the pages dir but I'm not sure that solves the issue of the blog.

Thinking through this and considering options.

**Comment by kaf-lamed-beyt** [comment]
Yes. The tool I intend on using is [next-mdx-remote](https://github.com/hashicorp/next-mdx-remote). 

Although, they have a module dedicated to RSCs &mdash; more on that [here](https://github.com/hashicorp/next-mdx-remote?tab=readme-ov-file#react-server-components-rsc--nextjs-app-directory-support) &mdash; they consider it to be unstable. 

Thinking about it again now... I think next-mdx-remote could suit our use case here. In the sense that, we can have the markdown files somewhere else, perhaps in a GitHub repo where it can be fetched via GitHub's API (I'm not certain about this, just thinking out loud. But this is based on the premise of what the package does. Hence the "remote" in its name).

But, once again, it goes against what you already described pertaining this issue. Which is to make it filebased.

I've checked out [@next/mdx](https://www.npmjs.com/package/@next/mdx) as an alternative. It seemed a bit far-fetched from the file-based markdown approach you mentioned. You can take a loot at it still, perhaps I'm missing something.

**Comment by acekyd** [comment]
The more I think about this @kaf-lamed-beyt, the more likely it seems that the best course is to switch to a Pages dir layout. I'm uncertain how long that would take and if it'd make it possible to use Chakra UI with the markdown blog. 🤔

**Comment by kaf-lamed-beyt** [comment]
Switching to pages might take too long. I can try migrating. If it is going to take much longer I'll let you know. 

Let me know if this sounds good @acekyd.

**Comment by segunadebayo** [comment]
Thanks for reaching out @acekyd.

@kaf-lamed-beyt, the recommended composition pattern for RSC is to move client components down the tree as deeply as possible. [Read more here](https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#moving-client-components-down-the-tree)

Here's an example of how you can achieve the above

**Create a dedicated component** 

```tsx
// article.tsx

'use client'

import {  Box, Stack } from "@chakra-ui/react"

export function Article(props){
   return <Box></Box>
}

export function ArticleList(props){
   return <Stack></Stack>
}
```

**Use the client component in the app dir**. Notice how 'use client' is not added to this page.

```tsx
// app/articles/pages.tsx

import { readFile } from 'node:fs/promises'
import { ArticleList, Article } from "./article"

export default async function Page(){
     const files = path.join(process.cwd(), "/app/blog/articles");
     const data = await Promise.all(files.map(file=> readFile(file, 'uft-8')))
	return (
        <ArticleList>
           {data.map(item=> <Article data={item} />)}
        </ArticleList>
    )
}
```

**Comment by kaf-lamed-beyt** [comment]
Aha! I see. 

Data would be shared through the prop. @segunadebayo this is also going to be applicable if I want to render the slug route &mdash; `/app/blog/[slug]` &mdash; too, yeah?

**Comment by kaf-lamed-beyt** [comment]
Circling back to say this worked! @acekyd. I should have a PR open before Saturday.

Thank you, @segunadebayo!

**Comment by kaf-lamed-beyt** [comment]
Circling back to say this worked! @acekyd. I should have a PR open before Saturday.

Thank you, @segunadebayo!
