### ISSUE TITLE
Improve how projects data is fetched and made available in V2

### ISSUE THREAD

**Issue by acekyd** [acekyd/made-in-nigeria#268]
I don't use much Next but I currently fetch projects only on the Projects page however would love to do this in a way that makes the data available across state in the website. 

This will enable building components that could use the data in a user's profile on the blog for example. 

Open to recommendations or a PR. 

Current implementation can be found in [Projects](https://github.com/acekyd/made-in-nigeria/blob/3ab45368f936a0b776e74226a8296e6f074cf99e/app/projects/page.js#L5)

**Comment by kaf-lamed-beyt** [comment]
Okay... so, a profile can be tied to a project's owner?

**Comment by acekyd** [comment]
Yes and also hopefully make the website faster. And if someone goes to a direct link without going to the projects page, the data is also available. @kaf-lamed-beyt

**Comment by kaf-lamed-beyt** [comment]
Oh okay. makes sense now. 

I thought of an approach &mdash; tow actually &mdash; of accomplishing this. The first involves using a [Zustand](https://docs.pmnd.rs/zustand/getting-started/introduction) store to persist the project's data. 

The second encompasses the use of a shareable hook &mdash; perhaps, `useProjects()` &mdash; which would encapsulate the `getData` and `convertToJSON()` functions. So we'd just call the hook wherever we need it in the project.

**Comment by acekyd** [comment]
Yes I like the sound of the universal store so we can reuse the data anyhow we please. @kaf-lamed-beyt

**Comment by kaf-lamed-beyt** [comment]
Awesome! I'll try something out during the week and let you know how it goes.

**Comment by acekyd** [comment]
What questions do you have about this? @kaf-lamed-beyt

**Comment by kaf-lamed-beyt** [comment]
Okay... say we keep all the projects in a store, yeah? 

> This will enable building components that could use the data in a user's profile on the blog for example.
What's the relationship between those projects and the creators? Say, on the creators route for instance

**Comment by acekyd** [comment]
@kaf-lamed-beyt So the main goal is this - whichever page serves as the entry point for a user - could be a blog page, could be the about page, I'd want to load the projects in the background (and one time) so that wherever they navigate to after that is smoother. 

As regards the interoperability of the data with components / pages - for the creators, the routes would be their username e.g /creators/acekyd. And in that markdown, we can show projects that match their username. Or on the landing page we can randomly or manually select featured projects without having to run a http request. 

Not all of these features are currently available or will be on launch, but good to think of the data fetching with that in mind.

**Comment by kaf-lamed-beyt** [comment]
Aha! I see. Now I understand. I'll refactor the current store approach. If anything changes I'll let you know.

**Comment by acekyd** [comment]
Resolved in #272
