### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by williamolojede** [acekyd/made-in-nigeria#27]
Yo ace, wouldn't it be nice to add pagination since the link would keep growing?

**Comment by acekyd** [comment]
Yeah @williamolojede that could be looked into :)

**Comment by acekyd** [comment]
After consideration... I think pagination would not be required at this time since it fetches the whole data from the markdown for processing already... Thanks @williamolojede

**Comment by Jolaolu** [comment]
Hi Ace @acekyd, I think it would be nice to get something to help with the fatigue that comes with scrolling, if not pagination, it could be an infinite scroll implementation.
