### ISSUE TITLE
bug(UI): Alphabet filter component doesn't stick on scroll

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [acekyd/made-in-nigeria#284]
The current implementation of the alphabet filter uses the Intersection Observer API which should make the component become sticky on scroll. 

But, for now... it doesn't. I'll have a look again to see if I can raise a PR that addresses this.

**Comment by acekyd** [comment]
Aye! Just caught this as well. Thanks @kaf-lamed-beyt

**Comment by kaf-lamed-beyt** [comment]
Hi @acekyd. 

I've been quite occupied for a while now that's why I haven't been able to send a PR. when I'm less busy. I'll attend to it. :pray:
