### ISSUE TITLE
Add template for PRs and Issues

### ISSUE THREAD

**Issue by rotimi-best** [acekyd/made-in-nigeria#299]
I think there should be a template for issues and PRs so every new contributor can follow a guideline for consistency.

For my project [classroomio](https://github.com/rotimi-best/classroomio) we have both [issues](https://github.com/rotimi-best/classroomio/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml) and [PR](https://github.com/rotimi-best/classroomio/blob/main/.github/PULL_REQUEST_TEMPLATE.md) templates.

I am also willing to work on this issue.

Please let me know if I should implement something similar or you have a specific template in mind.

**Comment by acekyd** [comment]
I'd love that. Thanks @rotimi-best
