### ISSUE TITLE
Creators page bug on screen greater than 1279

### ISSUE THREAD

**Issue by rotimi-best** [acekyd/made-in-nigeria#300]
### Current result
1. Go to `/creators/prosper-otemuyiwa`
2. On screen width less than 1279, everything looks fine
<img width="1276" alt="image" src="https://github.com/acekyd/made-in-nigeria/assets/31730715/8c8c881f-fb21-460c-ab96-00dd5a630909">
3. On screen width greater than 1279, the UI goes back into mobile
<img width="1172" alt="image" src="https://github.com/acekyd/made-in-nigeria/assets/31730715/67f9084e-6393-403f-a755-4dd61331499a">

### Expected result
1. On screen greater than 1279, the content shouldn't shrink to mobile.

## Video
Here is a jam.dev link show the error: https://jam.dev/c/cce7f08c-aba9-4c2e-9e0a-2aff83fdc600

**Comment by kaf-lamed-beyt** [comment]
Hi @rotimi-best, mind submitting a PR that addresses this?

**Comment by rotimi-best** [comment]
@kaf-lamed-beyt, gladly 👍🏽

**Comment by rotimi-best** [comment]
This issue has been fixed on production.
<img width="1536" alt="image" src="https://github.com/acekyd/made-in-nigeria/assets/31730715/8611a26d-1c29-45ae-b0fc-da4cdeb91c7e">
