### ISSUE TITLE
Third column of project list is cutting out

### ISSUE THREAD

**Issue by rotimi-best** [acekyd/made-in-nigeria#304]
On the project list [page](https://www.madeinnigeria.dev/projects), the 3rd item on each row seems to be cut out.

<img width="1273" alt="Screenshot 2024-03-07 at 7 52 13 AM" src="https://github.com/acekyd/made-in-nigeria/assets/31730715/a1111100-7f22-4c05-929f-b5e1c6469720">

**Comment by kaf-lamed-beyt** [comment]
True. 

Thank you for this. I look forward to your PR! 🚀

**Comment by samuelogboye** [comment]
If this issue is fixed, I think it should be closed
@rotimi-best @adebiyial @kaf-lamed-beyt
