### ISSUE TITLE
Report of Constant page Reloading Issue on route https://www.madeinnigeria.dev/projects

### ISSUE THREAD

**Issue by MdialloC19** [acekyd/made-in-nigeria#315]
### Issue Description

I have noticed that the **website frequently reloads itself without any apparent reason on route https://www.madeinnigeria.dev/projects ,** which disrupts the user experience and makes it difficult to navigate the content seamlessly.
This reloading issue occurs consistently across different browsers and devices, suggesting that it may be a systemic problem rather than a localized issue. I have also cleared my browser cache and cookies, but the problem persists.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by acekyd** [comment]
Hey thanks for catching this. Looking into it asap.

**Comment by acekyd** [comment]
Thanks for the catch @dro-1, it doesn't reload locally but I'm assuming a new push has broken it yet again. 😅
