### ISSUE TITLE
Projects Begining with L do not show

### ISSUE THREAD

**Issue by othreecodes** [acekyd/made-in-nigeria#51]
![screenshot from 2017-07-01 22-19-10](https://user-images.githubusercontent.com/18391371/27765626-9b59dd0a-5eae-11e7-88d7-0e6713416aa3.png)

The Data for content in the `L` Section doesn't show Due to some errors in the `README.MD` file

**Comment by acekyd** [comment]
Thanks @othreecodes I didn't notice. Any idea what really caused it? I couldn't tell

**Comment by codehakase** [comment]
@othreecodes I think your browser may be the culprit, i'm on chrome 56.x.x and it shows that section
![min](https://user-images.githubusercontent.com/9336187/27768134-0177be9a-5f04-11e7-83d1-3ac1b77327e5.png)

**Comment by acekyd** [comment]
Yeah @codehakase The fix is already live.

**Comment by othreecodes** [comment]
@acekyd  its the way users added their repos, the format is `## <a name="L"> </a>L`  then a space below then after the space the repos should come under with no space between them. This particular entry was the culprit.

* [Linda ORM](https://github.com/solutionstack/Linda) -A light weight and fast Active-record based ORM for PHP   **By [@solutionstack](https://github.com/solutionstack)

It wasn't formatted well and it had a space below it.

The "W" part had the same spacing issue 


## <a name="W"> </a>W
* [web-crawljs](https://github.com/kayslay/web-crawljs) - A web crawler package for Nodejs that makes it easy to crawl web pages **By [@Kayslaycode](https://twitter.com/Kayslaycode)**

* [WordPress Persist Admin Notices Dismissal](https://github.com/collizo4sky/persist-admin-notices-dismissal) - Simple plugin that persists dismissal of admin notices across pages in WordPress dashboard. **By [@w3guy](https://twitter.com/w3guy)**

* [wtfoperamini](https://github.com/ireade/wtfoperamini) - Development features not supported in Opera Mini, and some crowsourced workarounds for them. **By [@ireaderinokun](https://twitter.com/ireaderinokun)**

It should look something like this instead

## <a name="W"> </a>W

* [web-crawljs](https://github.com/kayslay/web-crawljs) - A web crawler package for Nodejs that makes it easy to crawl web pages **By [@Kayslaycode](https://twitter.com/Kayslaycode)**
* [WordPress Persist Admin Notices Dismissal](https://github.com/collizo4sky/persist-admin-notices-dismissal) - Simple plugin that persists dismissal of admin notices across pages in WordPress dashboard. **By [@w3guy](https://twitter.com/w3guy)**
* [wtfoperamini](https://github.com/ireade/wtfoperamini) - Development features not supported in Opera Mini, and some crowsourced workarounds for them. **By [@ireaderinokun](https://twitter.com/ireaderinokun)**


This should probably be added to the contribution guidelines.

**Comment by acekyd** [comment]
Awesome... Its something we have to look out for during merges. Thanks @othreecodes
