### ISSUE TITLE
Check your content

### ISSUE THREAD

**Issue by equinusocio** [acekyd/made-in-nigeria#69]
Atom Material Palenight Syntax is a cloned themed from the original one called Material Theme (both for Sublime Text, Visual Studio Code and Hyper App) made in 2015.
- https://github.com/equinusocio/vsc-material-theme
- https://github.com/equinusocio/material-theme
- https://github.com/equinusocio/hyper-material-theme

It violated the original Material Theme license and i suggest you to remove this shit content.

**Comment by equinusocio** [comment]
Close without comments. Very nice.

**Comment by whizkydee** [comment]
Please head over to Twitter. Don't cause any issues here.

**Comment by equinusocio** [comment]
The issue is your cloned theme. So the issue is every channel where you share your cloned theme until you change the name of this shame. The issue is where people keep sharing this clone as your work. Don’t force me to require a github takedown.

**Comment by acekyd** [comment]
Wow this is serious. I understand any issues you might have @equinusocio but I don't think this is the place to do it. Unless you can precisely state how he has violated the license on your project or proof that it's a copy of your project, I don't think you have the right to demand it's removal. I'll be looking forward to your response so we can resolve this properly. Thanks.

**Comment by unicodeveloper** [comment]
@whizkydee First, I don't think it was right to just close the issue without any form of reply or conversation. That screams guilt at first sight.

@equinusocio I'm a proud user of Material theme for Sublime Text. Been using it for about a year now. Big fan. Concerning this current issue, I am looking at the MIT license you used. 

> MIT licenses allow others to modify & re-use your software freely without RESTRICTIONS. I use the license for all my projects.

Both of you use these licenses for both projects. So, if @whizkydee cloned your theme and modified it, made improvements or changes & released it as a new software/tool, then there is actually no problem here unless it's specifically stated that your name/brand should be included in every software that is released using your code or you should be given some form of credit. And in this situation, I don't think this is the case. Correct me if I am wrong.

Many times developers build upon other people's code and release them as new software. It is these licenses that make us sane in the community & prevent people from branding or stealing our work.

@equinusocio I totally understand how painful it is for someone to allegedly parade your work as theirs and it's totally valid to call them out once it's obvious. But open source can really be tricky. If you allow people access to copy, modify and redistribute without EXPLICITLY requesting some of credit anywhere in the project or license, then you have the right to be mad but also automatically lose the right to lash out or complain or request for a Github take-down.

Quick questions:

* What was the original Material theme license? 
* When was it changed?
* Was this project forked from the material theme project when the original license was in existence?
* Is the current material palenight code the same with @whizkydee's material palenight code?

Again guys, open source can be tricky. We all know what happened with **ReactJS** patent license. I hope we can sort this out amicably. 

#OpenSourceForTheWin ❤️ 

<img width="934" alt="screen shot 2017-10-14 at 4 21 43 pm" src="https://user-images.githubusercontent.com/2946769/31580127-cd053c56-b0fb-11e7-9585-343236031f84.png">


![mitlicense](https://user-images.githubusercontent.com/2946769/31580112-7f39ab24-b0fb-11e7-8788-e9f3d4987830.png)

**Comment by neoighodaro** [comment]
Well said @unicodeveloper. Licenses are important. Most times people as licenses without reading them. MIT allows for copying and modifications. @whizkydee says his theme was built from scratch. It's open source so you can verify this claim. 

Either way I think you both should pay attention to your licensing next time you both have great themes for different platforms.

And also @whizkydee it was wrong to close the issue without a response.

**Comment by equinusocio** [comment]
@unicodeveloper  Hi, **vsc-material-theme** was under Apache 2.0 license until yesterday
- [first commit](https://github.com/equinusocio/vsc-material-theme/commit/293bf07b07751cc50a759959abf699c99ccea771#diff-9879d6db96fd29134fc802214163b95a)
- [Yesterday commit](https://github.com/equinusocio/vsc-material-theme/commit/c9021d2b0dcf5bab30856f5624e69d650adf2b27#diff-9879d6db96fd29134fc802214163b95a)

**I changed yesterday this the license because i'm collaborating with other **honest guys**. But when was cloned was under apache 2.0 license. And right now i will restore this license.
 By the way MIT license require to add **License and copyright notice** as credit/link to the original work. And i don't see anything similar in the cloned repository. 
So anyway it created a software that look pretty identical with another license type. I don't care about code.**

I just asked the author to rename his projects since is misleading and cause confusion (just because my material theme was created 2 years ago) it was not ok with that. 

If you make a clone of an apple computer keeping the same name but changing materials is still a clone.

**Comment by ammezie** [comment]
@equinusocio I Know you put much work on the Material Theme (huge fan of it BTW) but I think you should have contacted him personally before opening this issue. It could've been settled amicably without escalating to this issue.

@whizkydee as already pointed by others, it was wrong closing the issue without a comment.

**Comment by equinusocio** [comment]
@ammezie I just asked the author to rename his projects since is misleading and cause confusion (just because my material theme was created 2 years ago) it was not ok with that...

**Comment by iykyvic** [comment]
Not much to say here, we should all embrace actionable specific and kind feedback when dealing with issues like this.

**Comment by acekyd** [comment]
Are we good to close this?
