### ISSUE TITLE
Incomplete description of Fawn on the website

### ISSUE THREAD

**Issue by e-oj** [acekyd/made-in-nigeria#84]
I noticed the description of Fawn on the website is incomplete. It just says "phase commits" which doesn't really describe the project. I'd appreciate it a lot if that gets changed

**Comment by whizkydee** [comment]
Hi @e-oj,

Thanks for reporting this. It's strange though. I'll look into it soon.

**Comment by acekyd** [comment]
Fixed with f9a1e33
